---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gears
  labels:
    serviceType: gears
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      name: gears
      labels:
        serviceType: gears
    spec:
      containers:
        - name: gears
          image: transformers/gears:latest
          imagePullPolicy: Never
          ports:
          - containerPort: 8080
          env:
          - name: JAVA_OPTS
            value: -Xmx64m -Xms64m
          - name: SPRING_APPLICATION_NAME
            value: "gears"
          - name: TRANSFORMER_MODE
            valueFrom:
              configMapKeyRef:
                name: autobots-config
                key: transformer.mode
---
apiVersion: v1
kind: Service
metadata:
  name: gears-entrypoint
  namespace: default
spec:
  selector:
    serviceType: gears
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30081
  type: NodePort