---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: megatron
  labels:
    serviceType: megatron
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      name: megatron
      labels:
        serviceType: megatron
    spec:
      containers:
        - name: megatron
          image: transformers/megatron:latest
          imagePullPolicy: Never
          ports:
          - containerPort: 8080
          env:
          - name: JAVA_OPTS
            value: -Xmx64m -Xms64m
          - name: SPRING_APPLICATION_NAME
            value: "megatron"
          - name: TRANSFORMER_MODE
            valueFrom:
              configMapKeyRef:
                name: decepticons-config
                key: transformer.mode
---
apiVersion: v1
kind: Service
metadata:
  name: megatron-entrypoint
  namespace: default
spec:
  selector:
    serviceType: megatron
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30082
  type: NodePort